//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch.Epyx.WindMobile.WP7.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ch.Epyx.WindMobile.WP7.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string ApplicationBar_Send {
            get {
                return ResourceManager.GetString("ApplicationBar_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1h.
        /// </summary>
        public static string Chart_Button_1h {
            get {
                return ResourceManager.GetString("Chart_Button_1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24h.
        /// </summary>
        public static string Chart_Button_24h {
            get {
                return ResourceManager.GetString("Chart_Button_24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6h.
        /// </summary>
        public static string Chart_Button_6h {
            get {
                return ResourceManager.GetString("Chart_Button_6h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        public static string Chart_Title_Average {
            get {
                return ResourceManager.GetString("Chart_Title_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string Chart_Title_Max {
            get {
                return ResourceManager.GetString("Chart_Title_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. \r\nThe network may not be available.\r\n Please restart later..
        /// </summary>
        public static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to recover data for station {0}..
        /// </summary>
        public static string Error_NoDataForStation {
            get {
                return ResourceManager.GetString("Error_NoDataForStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to recover message. Please check your network and try again later.
        /// </summary>
        public static string Error_NoMessage {
            get {
                return ResourceManager.GetString("Error_NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullscreen.
        /// </summary>
        public static string Full_Screen {
            get {
                return ResourceManager.GetString("Full_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string Header_Map {
            get {
                return ResourceManager.GetString("Header_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations.
        /// </summary>
        public static string Header_Stations {
            get {
                return ResourceManager.GetString("Header_Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string Menu_Map {
            get {
                return ResourceManager.GetString("Menu_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception.
        /// </summary>
        public static string PageName_Excpetion {
            get {
                return ResourceManager.GetString("PageName_Excpetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageName_Settings {
            get {
                return ResourceManager.GetString("PageName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to station list.
        /// </summary>
        public static string PageName_StationList {
            get {
                return ResourceManager.GetString("PageName_StationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Settings_Nickname {
            get {
                return ResourceManager.GetString("Settings_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Settings_UserName {
            get {
                return ResourceManager.GetString("Settings_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind last hour.
        /// </summary>
        public static string StartionData_WindLastHour {
            get {
                return ResourceManager.GetString("StartionData_WindLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string StationData_Air {
            get {
                return ResourceManager.GetString("StationData_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degree.
        /// </summary>
        public static string StationData_Air_Degree {
            get {
                return ResourceManager.GetString("StationData_Air_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string StationData_Air_Humidity {
            get {
                return ResourceManager.GetString("StationData_Air_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % relative.
        /// </summary>
        public static string StationData_Air_Relative {
            get {
                return ResourceManager.GetString("StationData_Air_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string StationData_Air_Temperature {
            get {
                return ResourceManager.GetString("StationData_Air_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitud.
        /// </summary>
        public static string StationData_Altitud {
            get {
                return ResourceManager.GetString("StationData_Altitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string StationData_Average {
            get {
                return ResourceManager.GetString("StationData_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string StationData_Kmh {
            get {
                return ResourceManager.GetString("StationData_Kmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string StationData_Maximum {
            get {
                return ResourceManager.GetString("StationData_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string StationData_Minimum {
            get {
                return ResourceManager.GetString("StationData_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string StationData_Wind {
            get {
                return ResourceManager.GetString("StationData_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind max.
        /// </summary>
        public static string StationData_WindMax {
            get {
                return ResourceManager.GetString("StationData_WindMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend.
        /// </summary>
        public static string StationData_WindTrend {
            get {
                return ResourceManager.GetString("StationData_WindTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string TimeAgo_Day {
            get {
                return ResourceManager.GetString("TimeAgo_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeAgo_Hour {
            get {
                return ResourceManager.GetString("TimeAgo_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeAgo_Minutes {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a few seconds ago.
        /// </summary>
        public static string TimeAgo_Seconds {
            get {
                return ResourceManager.GetString("TimeAgo_Seconds", resourceCulture);
            }
        }
    }
}
